const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const { safeStorage, clipboard } = require('electron');
const { HistoryStore } = require('../history-store.cjs');
exports.run = async ({ main, overlay, app, engineEvent, testOverlayActions }) => {
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const evaluate = code => main.webContents.executeJavaScript(code);
  const directory = path.join(__dirname, '..', 'artifacts'); await fs.mkdir(directory, { recursive: true });
  const { history } = require('./fixtures.cjs');
  const originalRecordingStarted = history[0].metrics.started;
  const store = new HistoryStore(path.join(directory, 'test-history.sqlite'), safeStorage);
  const wav = Buffer.from('RIFF-test-WAVE-audio');
  history[0].alternatives = [{ id: 'alternate-gpt', text: 'An alternate GPT transcript.', rawText: 'An alternate GPT transcript.', metrics: { ...history[0].metrics, started: new Date(Date.parse(originalRecordingStarted) + 60000).toISOString(), costs: [], transcriptionModel: 'gpt-transcribe', cleanupMode: 'off' } }];
  await store.write(history, new Map([[history[0].id, { bytes: wav, format: 'wav' }]]));
  assert.deepEqual(await new HistoryStore(store.file, safeStorage).read(), history.map((entry, index) => ({ ...entry, hasAudio: index === 0 })));
  assert.deepEqual(await new HistoryStore(store.file, safeStorage).readAudio(history[0].id), { bytes: wav, format: 'wav' });
  assert(!(await fs.readFile(store.file)).includes(Buffer.from(history[0].text)));
  assert((await fs.readFile(store.file)).includes(wav));
  const firstLedger = { through: '2026-09-14T00:00:00Z', importedAt: '2026-09-15T12:00:00Z', rows: [
    { date: '2026-09-14', category: 'voice', model: 'microsoft/mai-transcribe-2', provider: 'Azure', endpoint: 'ep-1', amount: 0.01, requests: 4 }
  ] };
  await store.replaceCostLedger(firstLedger);
  assert.deepEqual(await new HistoryStore(store.file, safeStorage).readCostLedger(), firstLedger);
  await store.replaceCostLedger({ ...firstLedger, rows: [{ ...firstLedger.rows[0], amount: 0.02 }] });
  assert.equal((await store.readCostLedger()).rows[0].amount, 0.02);
  const legacyFile = path.join(directory, 'legacy-history.bin');
  const migratedFile = path.join(directory, 'migrated-history.sqlite');
  await fs.rm(migratedFile, { force: true });
  await fs.writeFile(legacyFile, safeStorage.encryptString(JSON.stringify(history)));
  assert.deepEqual(await new HistoryStore(migratedFile, safeStorage, legacyFile).read(), history.map(entry => ({ ...entry, hasAudio: false })));
  await new HistoryStore(migratedFile, safeStorage, legacyFile).write([]);
  assert.deepEqual(await new HistoryStore(migratedFile, safeStorage, legacyFile).read(), []);
  engineEvent({ type: 'history', history });
  await wait(600);
  assert.equal(await evaluate('document.querySelectorAll(".transcript").length'), 4);
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="Show transcription details"]\').length'), 4);
  assert((await evaluate('document.querySelector(".transcript-meta .meta-popover").textContent')).includes('MAI-Transcribe-2 · Clean'));
  assert((await evaluate('document.querySelector(".transcript-meta .meta-popover").textContent')).includes('Luna'));
  assert((await evaluate('document.querySelector(".transcript-meta .meta-popover").textContent')).includes('Response'));
  assert((await evaluate('document.querySelector(".transcript-meta .meta-popover").textContent')).includes('Audio'));
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="Play audio"]\').length'), 1);
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="Download audio"]\').length'), 1);
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="No saved audio"]\').length'), 6);
  assert.equal(await evaluate('document.querySelectorAll(\'button[aria-label="Compare transcripts"]\').length'), 1);
  await evaluate('document.querySelector(\'button[aria-label="Compare transcripts"]\').click()'); await wait(100);
  assert.equal(await evaluate('document.getElementById("comparison-drawer").hidden'), false);
  assert.equal(await evaluate('document.querySelectorAll(".transcript-version").length'), 2);
  assert((await evaluate('document.getElementById("comparison-versions").textContent')).includes('An alternate GPT transcript.'));
  assert.equal(await evaluate('document.querySelector(\'[data-alternate-id="alternate-gpt"] [data-action="make-primary"]\').textContent'), 'Make primary');
  await evaluate('document.getElementById("alternate-model").value="mai-transcribe-2-verbatim"; document.getElementById("create-alternate").click()'); await wait(150);
  assert.equal(await evaluate('document.querySelectorAll(".transcript-version").length'), 3);
  assert((await evaluate('document.getElementById("comparison-versions").textContent')).includes('Alternate from mai-transcribe-2-verbatim.'));
  await fs.writeFile(path.join(directory, 'comparison.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate('document.querySelector(\'[data-alternate-id="alternate-gpt"] [data-action="make-primary"]\').click()'); await wait(150);
  assert.equal(await evaluate('document.querySelector(".transcript-version .transcript-text").textContent'), 'An alternate GPT transcript.');
  assert.equal(await evaluate(`window.whisper.call('initial').then(x => x.history.find(entry => entry.id === 'demo-0').metrics.started)`), originalRecordingStarted);
  await evaluate('document.getElementById("close-comparison").click()');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(\'[aria-label="No saved audio"]\')).cursor'), 'default');
  assert.equal(await evaluate('document.getElementById("balance-amount").textContent'), '$18.42');
  assert.equal(await evaluate('document.getElementById("cost-voice").textContent'), '$0.0212');
  assert.equal(await evaluate('document.getElementById("cost-cleanup").textContent'), '$0.0038');
  await evaluate('document.querySelector(".cost-info").focus()');
  assert.equal(await evaluate('getComputedStyle(document.getElementById("cost-model-breakdown")).display'), 'grid');
  assert((await evaluate('document.getElementById("cost-model-breakdown").textContent')).includes('MAI-Transcribe-2'));
  assert((await evaluate('document.getElementById("cost-model-breakdown").textContent')).includes('last imported 30 completed days'));
  engineEvent({ type: 'stats', stats: { total: 83, today: 83, last7Days: 83 }, costs: {
    voice: 0.0042, cleanup: 0.0008, voiceCount: 4, cleanupCount: 2, source: 'history',
    models: [{ category: 'voice', model: 'microsoft/mai-transcribe-2', amount: 0.0042 }, { category: 'cleanup', model: 'openai/gpt-5.6-luna', amount: 0.0008 }]
  } });
  await wait(50);
  assert.equal(await evaluate('document.getElementById("cost-voice").textContent'), '—');
  assert.equal(await evaluate('document.getElementById("cost-cleanup").textContent'), '—');
  assert((await evaluate('document.getElementById("cost-model-breakdown").textContent')).includes('Import OpenRouter activity'));
  assert(!overlay.isVisible());
  await fs.writeFile(path.join(directory, 'history.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate(`document.querySelector('[aria-label="Show performance"]').click()`); await wait(200);
  assert.equal(await evaluate('document.querySelectorAll("[data-stage=Recording]").length'), 0);
  assert.equal(await evaluate('document.getElementById("latency-value").textContent'), '1.36 s');
  await fs.writeFile(path.join(directory, 'performance.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate('document.getElementById("include-recording").click()'); await wait(100);
  assert.equal(await evaluate('document.querySelectorAll("[data-stage=Recording]").length'), 1);
  await evaluate('document.getElementById("close-drawer").click(); document.getElementById("search").value="tomorrow"; document.getElementById("search").dispatchEvent(new Event("input"))');
  assert.equal(await evaluate('document.querySelectorAll(".transcript").length'), 1);
  const previousClipboard = await clipboard.readText();
  await evaluate(`document.querySelector('[aria-label="Copy transcript"]').click()`); await wait(100);
  assert.equal(await evaluate('document.getElementById("toast").textContent'), 'Transcript copied');
  assert.equal(await clipboard.readText(), history[1].text);
  await clipboard.writeText('sentinel-before-paste');
  engineEvent({ type: 'transcript', entry: { id: 'pasted-ok', text: 'Pasted into the focused field.', metrics: { ...history[0].metrics, outcome: 'Pasted' } } });
  await wait(100);
  assert.equal(await clipboard.readText(), 'sentinel-before-paste');
  engineEvent({ type: 'transcript', entry: { id: 'focus-lost', text: 'Focus moved before paste.', metrics: { ...history[0].metrics, outcome: 'Saved to history' } } });
  await wait(100);
  assert.equal(await clipboard.readText(), 'Focus moved before paste.');
  assert.equal(await evaluate('document.getElementById("toast").textContent'), "Couldn't paste. Your transcript was copied to the clipboard.");
  await clipboard.writeText('sentinel-before-copylast');
  assert.equal(await evaluate("window.whisper.call('copyLast')"), true);
  assert.equal(await clipboard.readText(), 'Focus moved before paste.');
  await clipboard.writeText(previousClipboard);
  await evaluate('document.querySelector("[data-view=settings]").click()');
  assert.equal(await evaluate('document.getElementById("lock-mode").checked'), true);
  await evaluate('document.getElementById("lock-mode").click()'); await wait(100);
  assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.lockMode)"), false);
  await evaluate('document.getElementById("lock-mode").click()'); await wait(100);
  assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.lockMode)"), true);
  assert.equal(await evaluate('document.getElementById("transcription-model").value'), 'mai-transcribe-2-clean');
  assert.equal(await evaluate('document.getElementById("cleanup-mode").value'), 'off');
  assert.equal(await evaluate('document.getElementById("dictionary-terms").value'), '');
  await evaluate(`document.getElementById('xai-api-key').value='xai-test-only'; document.getElementById('settings-form').requestSubmit(document.querySelector('[type=submit]'))`);
  await wait(100);
  assert.equal(await evaluate('document.getElementById("xai-api-key").value'), '');
  assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.hasXaiKey)"), true);
  await evaluate(`document.getElementById('management-key').value='test-management-key'; document.getElementById('import-costs').click()`);
  await wait(100);
  assert.equal(await evaluate('document.getElementById("management-key").value'), '');
  assert((await evaluate('document.getElementById("import-costs-status").textContent')).includes('Delete the temporary key'));
  assert(!(await fs.readFile(path.join(app.getPath('userData'), 'history.sqlite'))).includes(Buffer.from('test-management-key')));
  assert.equal(await evaluate('document.getElementById("cost-voice").textContent'), '$0.0242');
  assert.equal(await evaluate('document.getElementById("cost-cleanup").textContent'), '$0.0048');
  await evaluate(`document.getElementById("dictionary-terms").value="Acme Corp\\n  Maya's project  \\n\\nmeeting notes"; document.getElementById("settings-form").requestSubmit(document.querySelector("[type=submit]"))`);
  await wait(100);
  assert.deepEqual(await evaluate("window.whisper.call('initial').then(x => x.settings.dictionaryTerms)"), ['Acme Corp', "Maya's project", 'meeting notes']);
  await evaluate('document.getElementById("dictionary-terms").value=""; document.getElementById("settings-form").requestSubmit(document.querySelector("[type=submit]"))');
  await wait(100);
  assert.deepEqual(await evaluate("window.whisper.call('initial').then(x => x.settings.dictionaryTerms)"), []);
  await evaluate('document.getElementById("dictionary-terms").value="Astra\\nExisting term"; document.getElementById("import-wispr").click()'); await wait(100);
  assert.deepEqual(await evaluate("window.whisper.call('initial').then(x => x.settings.dictionaryTerms)"), ['Astra', 'Existing term', 'Wispr Flow']);
  assert.equal(await evaluate('document.getElementById("import-wispr-status").textContent'), '1 new term imported. 3 snippets were skipped.');
  for (const model of ['mai-transcribe-2-verbatim', 'mai-transcribe-2-clean', 'gpt-transcribe', 'grok-voice-transcribe-2-streaming']) {
    await evaluate(`document.getElementById('transcription-model').value=${JSON.stringify(model)}; document.getElementById('settings-form').requestSubmit(document.querySelector('[type=submit]'))`);
    await wait(100);
    assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.transcriptionModel)"), model);
  }
  assert.equal(await evaluate('document.getElementById("live-chunks").disabled'), true);
  await evaluate("document.getElementById('transcription-model').value='mai-transcribe-2-clean'; document.getElementById('transcription-model').dispatchEvent(new Event('change'))");
  assert.equal(await evaluate('document.getElementById("cleanup-mode").disabled'), false);
  assert.equal(await evaluate('document.getElementById("live-chunks").disabled'), false);
  assert.equal(await evaluate('document.getElementById("double-transcription").disabled'), false);
  await evaluate("document.getElementById('double-transcription').checked=true; document.getElementById('settings-form').requestSubmit(document.querySelector('[type=submit]'))");
  await wait(100);
  assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.doubleTranscription)"), true);
  await evaluate("document.getElementById('transcription-model').value='mai-transcribe-2-clean'; document.getElementById('transcription-model').dispatchEvent(new Event('change'))");
  for (const mode of ['luna', 'luna-fast', 'off']) {
    await evaluate(`document.getElementById('cleanup-mode').value=${JSON.stringify(mode)}; document.getElementById('settings-form').requestSubmit(document.querySelector('[type=submit]'))`);
    await wait(100);
    assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.cleanupMode)"), mode);
  }
  engineEvent({ type: 'transcript', entry: { id: 'cleaned', text: 'Profits rose 70%.', rawText: 'Profits rose 50%, no, 70%.', metrics: { ...history[0].metrics, rows: [...history[0].metrics.rows, { name: 'AI cleanup (Luna)', startMs: 18700, durationMs: 500 }] } } });
  await evaluate(`document.querySelector('[data-view=history]').click(); document.getElementById('search').value=''; document.getElementById('search').dispatchEvent(new Event('input')); document.querySelector('[data-id=cleaned] [aria-label="Show performance"]').click()`);
  await wait(100);
  assert.equal(await evaluate('document.querySelectorAll(\'[data-stage="AI cleanup (Luna)"]\').length'), 1);
  assert.equal(await evaluate('document.getElementById("original-text").textContent'), 'Profits rose 50%, no, 70%.');
  assert.equal(await evaluate('document.getElementById("original-transcript").hidden'), false);
  assert(Number((await evaluate('document.getElementById("words-total").textContent')).replaceAll(',', '')) > 0);
  await evaluate('document.getElementById("close-drawer").click(); document.querySelector("[data-view=settings]").click()');
  await wait(200);
  await fs.writeFile(path.join(directory, 'settings.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate('document.getElementById("dictionary-terms").scrollIntoView({block:"center"})');
  await wait(150);
  await fs.writeFile(path.join(directory, 'dictionary.png'), (await main.webContents.capturePage()).toPNG());
  engineEvent({ type: 'state', mode: 'PushToTalk', level: .18 }); await wait(200);
  assert(overlay.isVisible());
  assert.equal(overlay.isFocusable(), false);
  assert.deepEqual(overlay.getSize(), [192, 56]);
  assert.equal(await overlay.webContents.executeJavaScript('document.querySelectorAll(".bar").length'), 10);
  assert.equal(await overlay.webContents.executeJavaScript('document.body.innerText'), '');
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("cancel").hidden'), true);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("finish").hidden'), true);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("wave").className'), 'wave');
  engineEvent({ type: 'state', mode: 'Busy', phase: 'transcribing', level: 0 }); await wait(250);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("wave").className'), 'wave transcribing');
  assert.equal(await overlay.webContents.executeJavaScript('getComputedStyle(document.querySelector(".bar")).backgroundColor'), 'rgb(197, 204, 237)');
  engineEvent({ type: 'state', mode: 'Busy', phase: 'luna', level: 0 }); await wait(250);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("wave").className'), 'wave luna');
  assert.equal(await overlay.webContents.executeJavaScript('getComputedStyle(document.querySelector(".bar")).backgroundColor'), 'rgb(207, 191, 226)');
  engineEvent({ type: 'state', mode: 'LockMode', level: .18 }); await wait(100);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("wave").className'), 'wave');
  assert.equal(overlay.isFocusable(), false);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("cancel").hidden'), false);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("finish").hidden'), false);
  const finishPoint = await overlay.webContents.executeJavaScript('(() => { const r = document.getElementById("finish").getBoundingClientRect(); return { x: Math.round(r.x + r.width / 2), y: Math.round(r.y + r.height / 2) }; })()');
  overlay.webContents.sendInputEvent({ type: 'mouseDown', ...finishPoint, button: 'left', clickCount: 1 });
  overlay.webContents.sendInputEvent({ type: 'mouseUp', ...finishPoint, button: 'left', clickCount: 1 });
  await wait(50);
  assert.deepEqual(testOverlayActions, ['finish']);
  assert.equal(overlay.isFocusable(), false);
  await fs.writeFile(path.join(directory, 'overlay.png'), (await overlay.webContents.capturePage()).toPNG());
  engineEvent({ type: 'state', mode: 'Idle', level: 0 }); assert(!overlay.isVisible());
  console.log('PASS: Electron history, balance, search, copy, performance defaults, and text-free recording overlay');
  app.quit();
};
