const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const { safeStorage, clipboard } = require('electron');
const { HistoryStore } = require('../history-store.cjs');
exports.run = async ({ main, overlay, app, engineEvent, testOverlayActions }) => {
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const evaluate = code => main.webContents.executeJavaScript(code);
  const directory = path.join(__dirname, '..', 'artifacts'); await fs.mkdir(directory, { recursive: true });
  const { history } = require('./fixtures.cjs');
  const store = new HistoryStore(path.join(directory, 'test-history.sqlite'), safeStorage);
  const wav = Buffer.from('RIFF-test-WAVE-audio');
  await store.write(history, new Map([[history[0].id, { bytes: wav, format: 'wav' }]]));
  assert.deepEqual(await new HistoryStore(store.file, safeStorage).read(), history.map((entry, index) => ({ ...entry, hasAudio: index === 0 })));
  assert.deepEqual(await new HistoryStore(store.file, safeStorage).readAudio(history[0].id), { bytes: wav, format: 'wav' });
  assert(!(await fs.readFile(store.file)).includes(Buffer.from(history[0].text)));
  assert((await fs.readFile(store.file)).includes(wav));
  const legacyFile = path.join(directory, 'legacy-history.bin');
  const migratedFile = path.join(directory, 'migrated-history.sqlite');
  await fs.rm(migratedFile, { force: true });
  await fs.writeFile(legacyFile, safeStorage.encryptString(JSON.stringify(history)));
  assert.deepEqual(await new HistoryStore(migratedFile, safeStorage, legacyFile).read(), history.map(entry => ({ ...entry, hasAudio: false })));
  await new HistoryStore(migratedFile, safeStorage, legacyFile).write([]);
  assert.deepEqual(await new HistoryStore(migratedFile, safeStorage, legacyFile).read(), []);
  await wait(600);
  assert.equal(await evaluate('document.querySelectorAll(".transcript").length'), 4);
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="Play audio"]\').length'), 1);
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="Download audio"]\').length'), 1);
  assert.equal(await evaluate('document.querySelectorAll(\'[aria-label="No saved audio"]\').length'), 6);
  assert.equal(await evaluate('getComputedStyle(document.querySelector(\'[aria-label="No saved audio"]\')).cursor'), 'default');
  assert.equal(await evaluate('document.getElementById("balance-amount").textContent'), '$18.42');
  assert(!overlay.isVisible());
  await fs.writeFile(path.join(directory, 'history.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate(`document.querySelector('[aria-label="Show performance"]').click()`); await wait(200);
  assert.equal(await evaluate('document.querySelectorAll("[data-stage=Recording]").length'), 0);
  assert.equal(await evaluate('document.getElementById("latency-value").textContent'), '1.36 s');
  await fs.writeFile(path.join(directory, 'performance.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate('document.getElementById("include-recording").click()'); await wait(100);
  assert.equal(await evaluate('document.querySelectorAll("[data-stage=Recording]").length'), 1);
  await evaluate('document.getElementById("close-drawer").click(); document.getElementById("search").value="tomorrow"; document.getElementById("search").dispatchEvent(new Event("input"))');
  assert.equal(await evaluate('document.querySelectorAll(".transcript").length'), 1);
  const previousClipboard = await clipboard.readText();
  await evaluate(`document.querySelector('[aria-label="Copy transcript"]').click()`); await wait(100);
  assert.equal(await evaluate('document.getElementById("toast").textContent'), 'Transcript copied');
  assert.equal(await clipboard.readText(), history[1].text);
  await clipboard.writeText(previousClipboard);
  await evaluate('document.querySelector("[data-view=settings]").click()');
  assert.equal(await evaluate('document.getElementById("lock-mode").checked'), true);
  await evaluate('document.getElementById("lock-mode").click()'); await wait(100);
  assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.lockMode)"), false);
  await evaluate('document.getElementById("lock-mode").click()'); await wait(100);
  assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.lockMode)"), true);
  assert.equal(await evaluate('document.getElementById("transcription-model").value'), 'mai-transcribe-2-clean');
  assert.equal(await evaluate('document.getElementById("cleanup-mode").value'), 'off');
  assert.equal(await evaluate('document.getElementById("dictionary-terms").value'), '');
  await evaluate(`document.getElementById("dictionary-terms").value="Acme Corp\\n  Maya's project  \\n\\nmeeting notes"; document.getElementById("settings-form").requestSubmit(document.querySelector("[type=submit]"))`);
  await wait(100);
  assert.deepEqual(await evaluate("window.whisper.call('initial').then(x => x.settings.dictionaryTerms)"), ['Acme Corp', "Maya's project", 'meeting notes']);
  await evaluate('document.getElementById("dictionary-terms").value=""; document.getElementById("settings-form").requestSubmit(document.querySelector("[type=submit]"))');
  await wait(100);
  assert.deepEqual(await evaluate("window.whisper.call('initial').then(x => x.settings.dictionaryTerms)"), []);
  await evaluate('document.getElementById("dictionary-terms").value="Astra\\nExisting term"; document.getElementById("import-wispr").click()'); await wait(100);
  assert.deepEqual(await evaluate("window.whisper.call('initial').then(x => x.settings.dictionaryTerms)"), ['Astra', 'Existing term', 'Wispr Flow']);
  assert.equal(await evaluate('document.getElementById("import-wispr-status").textContent'), '1 new term imported. 3 snippets were skipped.');
  for (const model of ['mai-transcribe-2-verbatim', 'mai-transcribe-2-clean', 'gpt-transcribe']) {
    await evaluate(`document.getElementById('transcription-model').value=${JSON.stringify(model)}; document.getElementById('settings-form').requestSubmit(document.querySelector('[type=submit]'))`);
    await wait(100);
    assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.transcriptionModel)"), model);
  }
  for (const mode of ['luna', 'luna-fast', 'off']) {
    await evaluate(`document.getElementById('cleanup-mode').value=${JSON.stringify(mode)}; document.getElementById('settings-form').requestSubmit(document.querySelector('[type=submit]'))`);
    await wait(100);
    assert.equal(await evaluate("window.whisper.call('initial').then(x => x.settings.cleanupMode)"), mode);
  }
  engineEvent({ type: 'transcript', entry: { id: 'cleaned', text: 'Profits rose 70%.', rawText: 'Profits rose 50%, no, 70%.', metrics: { ...history[0].metrics, rows: [...history[0].metrics.rows, { name: 'AI cleanup (Luna)', startMs: 18700, durationMs: 500 }] } } });
  await evaluate(`document.querySelector('[data-view=history]').click(); document.getElementById('search').value=''; document.getElementById('search').dispatchEvent(new Event('input')); document.querySelector('[data-id=cleaned] [aria-label="Show performance"]').click()`);
  await wait(100);
  assert.equal(await evaluate('document.querySelectorAll(\'[data-stage="AI cleanup (Luna)"]\').length'), 1);
  assert.equal(await evaluate('document.getElementById("original-text").textContent'), 'Profits rose 50%, no, 70%.');
  assert.equal(await evaluate('document.getElementById("original-transcript").hidden'), false);
  assert(Number((await evaluate('document.getElementById("words-total").textContent')).replaceAll(',', '')) > 0);
  await evaluate('document.getElementById("close-drawer").click(); document.querySelector("[data-view=settings]").click()');
  await wait(200);
  await fs.writeFile(path.join(directory, 'settings.png'), (await main.webContents.capturePage()).toPNG());
  await evaluate('document.getElementById("dictionary-terms").scrollIntoView({block:"center"})');
  await wait(150);
  await fs.writeFile(path.join(directory, 'dictionary.png'), (await main.webContents.capturePage()).toPNG());
  engineEvent({ type: 'state', mode: 'PushToTalk', level: .18 }); await wait(200);
  assert(overlay.isVisible());
  assert.equal(overlay.isFocusable(), false);
  assert.deepEqual(overlay.getSize(), [192, 56]);
  assert.equal(await overlay.webContents.executeJavaScript('document.querySelectorAll(".bar").length'), 10);
  assert.equal(await overlay.webContents.executeJavaScript('document.body.innerText'), '');
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("cancel").hidden'), true);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("finish").hidden'), true);
  engineEvent({ type: 'state', mode: 'LockMode', level: .18 }); await wait(100);
  assert.equal(overlay.isFocusable(), false);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("cancel").hidden'), false);
  assert.equal(await overlay.webContents.executeJavaScript('document.getElementById("finish").hidden'), false);
  const finishPoint = await overlay.webContents.executeJavaScript('(() => { const r = document.getElementById("finish").getBoundingClientRect(); return { x: Math.round(r.x + r.width / 2), y: Math.round(r.y + r.height / 2) }; })()');
  overlay.webContents.sendInputEvent({ type: 'mouseDown', ...finishPoint, button: 'left', clickCount: 1 });
  overlay.webContents.sendInputEvent({ type: 'mouseUp', ...finishPoint, button: 'left', clickCount: 1 });
  await wait(50);
  assert.deepEqual(testOverlayActions, ['finish']);
  assert.equal(overlay.isFocusable(), false);
  await fs.writeFile(path.join(directory, 'overlay.png'), (await overlay.webContents.capturePage()).toPNG());
  engineEvent({ type: 'state', mode: 'Idle', level: 0 }); assert(!overlay.isVisible());
  console.log('PASS: Electron history, balance, search, copy, performance defaults, and text-free recording overlay');
  app.quit();
};
